# Generated by Django 6.0.5 on 2026-05-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_area_registroasistencia_actividad_diaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Oficina Principal', max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, help_text='Latitud de la oficina', max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, help_text='Longitud de la oficina', max_digits=9)),
                ('radio_permitido_metros', models.IntegerField(default=500, help_text='Radio permitido en metros para marcar asistencia')),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración GPS',
                'verbose_name_plural': 'Configuraciones GPS',
            },
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='latitud_entrada',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='latitud_salida',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='longitud_entrada',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='longitud_salida',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='precisión_entrada',
            field=models.FloatField(blank=True, help_text='Precisión GPS en metros', null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='precisión_salida',
            field=models.FloatField(blank=True, help_text='Precisión GPS en metros', null=True),
        ),
    ]
