# Generated by Django 6.0.5 on 2026-05-26 20:46

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_configuraciongps_registroasistencia_latitud_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ausenciaprogramada',
            name='aprobada',
        ),
        migrations.AddField(
            model_name='ausenciaprogramada',
            name='creada_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ausenciaprogramada',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='ausenciaprogramada',
            name='procesada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_procesados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configuraciongps',
            name='radio_permitido_metros',
            field=models.IntegerField(default=20, help_text='Radio permitido en metros para marcar asistencia'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('a_tiempo', 'A tiempo'), ('tardanza', 'Tardanza'), ('falta', 'Falta'), ('permiso', 'Permiso'), ('recuperacion', 'Recuperación')], default='a_tiempo', max_length=20),
        ),
        migrations.CreateModel(
            name='MetaHorasPracticante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_totales_requeridas', models.IntegerField(default=300, help_text='Total de horas de práctica requeridas')),
                ('fecha_inicio_practica', models.DateField()),
                ('fecha_fin_practica', models.DateField()),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_horas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de Horas',
                'verbose_name_plural': 'Metas de Horas',
            },
        ),
        migrations.CreateModel(
            name='RecuperacionDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_falta', models.DateField(help_text='Día que faltó')),
                ('horas_a_recuperar', models.DurationField(help_text='Horas que debe recuperar')),
                ('fecha_recuperacion', models.DateField(blank=True, help_text='Sábado en que recuperó', null=True)),
                ('horas_recuperadas', models.DurationField(default=datetime.timedelta(0))),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recuperado', 'Recuperado'), ('excluido', 'Excluido')], default='pendiente', max_length=20)),
                ('motivo_exclusion', models.CharField(blank=True, max_length=255)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recuperación de Día',
                'verbose_name_plural': 'Recuperaciones de Días',
                'ordering': ['-fecha_falta'],
            },
        ),
    ]
