# Generated by Django 6.0.5 on 2026-05-26 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_remove_ausenciaprogramada_aprobada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausenciaprogramada',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recuperaciondia',
            name='registro_falta',
            field=models.OneToOneField(blank=True, help_text='Falta original asociada a esta recuperación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperacion', to='asistencia.registroasistencia'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('rrhh', 'RRHH'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado')], default='empleado', max_length=20),
        ),
    ]
