# Generated by Django 6.0.5 on 2026-05-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_ausenciaprogramada_creada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codigo_qr',
            field=models.CharField(blank=True, editable=False, help_text='Código QR único del empleado para validar asistencia', max_length=50, null=True, unique=True),
        ),
    ]
