# Generated by Django 6.0.5 on 2026-05-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_customuser_codigo_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('rrhh', 'RRHH'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado'), ('pphh', 'Practicante (PP.HH.)')], default='empleado', max_length=20),
        ),
    ]
