# Generated by Django 6.0.5 on 2026-05-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_alter_configuraciongps_radio_permitido_metros'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='permite_entrada_tardia',
            field=models.BooleanField(default=False, help_text='Si permite marcar entrada después de la tardanza máxima'),
        ),
        migrations.AddField(
            model_name='horario',
            name='tardanza_maxima_minutos',
            field=models.IntegerField(default=30, help_text='Minutos máximos de tardanza permitidos antes de considerarse falta'),
        ),
        migrations.AddField(
            model_name='horario',
            name='tipo_horario',
            field=models.CharField(choices=[('fijo', 'Fijo'), ('flexible', 'Flexible'), ('rotativo', 'Rotativo'), ('nocturno', 'Nocturno')], default='fijo', max_length=20),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='minutos_tarde',
            field=models.IntegerField(default=0, help_text='Minutos de tardanza calculados'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='minutos_temprano',
            field=models.IntegerField(default=0, help_text='Minutos que llegó temprano (antes de la hora de entrada)'),
        ),
    ]
