# Generated by Django 6.0.5 on 2026-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0009_horario_permite_entrada_tardia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='tipo_entrada',
            field=models.CharField(choices=[('gps', 'GPS'), ('qr', 'QR Oficina'), ('manual', 'Manual / Red Local'), ('rrhh', 'Manual RRHH')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='tipo_salida',
            field=models.CharField(blank=True, choices=[('gps', 'GPS'), ('qr', 'QR Oficina'), ('manual', 'Manual / Red Local'), ('rrhh', 'Manual RRHH')], max_length=20, null=True),
        ),
    ]
